"use client";

/**
 * chat-vault: recent chats kept on the device, encrypted, so reopening the
 * app paints your threads at once instead of a skeleton (owner 2026-09-17).
 *
 * What it protects against, honestly:
 * - Records are AES-GCM encrypted with a key generated by WebCrypto as
 *   NON-EXTRACTABLE and kept in IndexedDB. The key object can be used by
 *   this origin but its bytes can never be read out, so the stored chats
 *   are unreadable to anything that copies the browser's files off disk,
 *   another browser profile, or a backup.
 * - Everything is scoped to one profile id. A different account signing in
 *   on the same browser gets its own key, and every other profile's
 *   records are deleted on the spot.
 * - Sign-out deletes the whole database.
 * - Records expire after 14 days, and chats that are no longer in your
 *   inbox are dropped.
 *
 * What it cannot protect against: script running on this origin while you
 * are signed in. Such script could read your chats through the API anyway,
 * so the vault adds no exposure there.
 *
 * What is stored: the newest 50 messages of the 30 most recently touched
 * threads, as the gateway sent them. Never media bytes, never optimistic
 * or failed sends. Every failure is silent: the vault is a speed-up, and
 * the network remains the source of truth.
 */

const DB_NAME = "ws-chat-vault";
const DB_VERSION = 1;
const KEYS = "keys";
const THREADS = "threads";
const TTL_MS = 14 * 24 * 60 * 60 * 1000;
const MAX_THREADS = 30;
const MAX_MESSAGES = 50;

interface ThreadRecord {
	id: string; // `${profileId}:${conversationId}`
	profileId: string;
	conversationId: string;
	iv: Uint8Array<ArrayBuffer>;
	data: ArrayBuffer;
	savedAt: number;
}

let dbPromise: Promise<IDBDatabase | null> | null = null;

function openDb(): Promise<IDBDatabase | null> {
	if (typeof indexedDB === "undefined" || typeof crypto?.subtle === "undefined") {
		return Promise.resolve(null);
	}
	if (dbPromise) return dbPromise;
	dbPromise = new Promise((resolve) => {
		// An open waits behind a pending delete, and a delete waits for every
		// connection to close, so one tab still running code without the
		// versionchange handler below would park this forever; and the chat's
		// open path awaits the vault. Give up quickly and run as if there were
		// no vault: the network is the source of truth anyway (found verifying
		// 2026-09-17).
		const timer = setTimeout(() => {
			dbPromise = null;
			resolve(null);
		}, 1200);
		const done = (db: IDBDatabase | null) => {
			clearTimeout(timer);
			resolve(db);
		};
		try {
			const req = indexedDB.open(DB_NAME, DB_VERSION);
			req.onupgradeneeded = () => {
				const db = req.result;
				if (!db.objectStoreNames.contains(KEYS)) db.createObjectStore(KEYS);
				if (!db.objectStoreNames.contains(THREADS)) {
					const s = db.createObjectStore(THREADS, { keyPath: "id" });
					s.createIndex("profileId", "profileId", { unique: false });
				}
			};
			req.onsuccess = () => {
				const db = req.result;
				// Another tab signing out deletes this database, and a delete
				// waits for every open connection to close. Without this, a
				// second WorldSpace tab held its connection forever, the wipe
				// never finished, and every later open queued behind it (hit
				// verifying 2026-09-17).
				db.onversionchange = () => {
					db.close();
					dbPromise = null;
					keyPromises.clear();
				};
				done(db);
			};
			req.onerror = () => done(null);
			req.onblocked = () => done(null);
		} catch {
			done(null);
		}
	});
	return dbPromise;
}

function tx<T>(
	db: IDBDatabase,
	store: string,
	mode: IDBTransactionMode,
	run: (s: IDBObjectStore) => IDBRequest<T> | void,
): Promise<T | undefined> {
	return new Promise((resolve) => {
		try {
			const t = db.transaction(store, mode);
			const req = run(t.objectStore(store));
			t.oncomplete = () => resolve(req ? (req.result as T) : undefined);
			t.onerror = () => resolve(undefined);
			t.onabort = () => resolve(undefined);
		} catch {
			resolve(undefined);
		}
	});
}

// One in-flight lookup per profile. Without it the first burst of saves
// (several threads at once) each found no key, each generated one, and each
// stored it over the last, so every thread but one was encrypted with a key
// that no longer existed (caught verifying 2026-09-17: OperationError on
// decrypt).
const keyPromises = new Map<string, Promise<CryptoKey | null>>();

function keyFor(db: IDBDatabase, profileId: string): Promise<CryptoKey | null> {
	const pending = keyPromises.get(profileId);
	if (pending) return pending;
	const p = (async () => {
		const existing = await tx<CryptoKey>(db, KEYS, "readonly", (s) => s.get(profileId));
		if (existing) return existing;
		try {
			const key = await crypto.subtle.generateKey(
				{ name: "AES-GCM", length: 256 },
				false, // non-extractable: usable here, never readable
				["encrypt", "decrypt"],
			);
			// add, not put: if another tab created one first, keep theirs.
			await tx(db, KEYS, "readwrite", (s) => s.add(key, profileId));
			const stored = await tx<CryptoKey>(db, KEYS, "readonly", (s) => s.get(profileId));
			return stored ?? null;
		} catch {
			return null;
		}
	})();
	keyPromises.set(profileId, p);
	// A failed lookup may be retried later.
	void p.then((k) => {
		if (!k) keyPromises.delete(profileId);
	});
	return p;
}

const isPersistable = (m: { _id?: string; failed?: boolean }) =>
	!!m._id && !m._id.startsWith("temp-") && !m.failed;

/** Save the newest page of one thread. */
export async function saveThread(
	profileId: string,
	conversationId: string,
	messages: { _id?: string; failed?: boolean }[],
): Promise<void> {
	const db = await openDb();
	if (!db || !profileId || !conversationId) return;
	const rows = messages.filter(isPersistable).slice(-MAX_MESSAGES);
	if (rows.length === 0) return;
	const key = await keyFor(db, profileId);
	if (!key) return;
	try {
		const iv = crypto.getRandomValues(new Uint8Array(12));
		const data = await crypto.subtle.encrypt(
			{ name: "AES-GCM", iv },
			key,
			new TextEncoder().encode(JSON.stringify(rows)),
		);
		const record: ThreadRecord = {
			id: `${profileId}:${conversationId}`,
			profileId,
			conversationId,
			iv,
			data,
			savedAt: Date.now(),
		};
		await tx(db, THREADS, "readwrite", (s) => s.put(record));
	} catch {
		/* a speed-up, never an error */
	}
}

/**
 * Every live thread saved for this profile, decrypted, newest first.
 * Also the housekeeping pass: removes other profiles' records and keys,
 * expired records, threads no longer in `keepIds`, and anything past the
 * thread cap.
 */
export async function loadThreads<M>(
	profileId: string,
	keepIds?: Set<string>,
): Promise<Record<string, M[]>> {
	const out: Record<string, M[]> = {};
	const db = await openDb();
	if (!db || !profileId) return out;
	const all = (await tx<ThreadRecord[]>(db, THREADS, "readonly", (s) => s.getAll())) ?? [];
	const now = Date.now();
	const mine = all
		.filter((r) => r.profileId === profileId)
		.sort((a, b) => b.savedAt - a.savedAt);
	const drop = new Set<string>();
	for (const r of all) if (r.profileId !== profileId) drop.add(r.id);
	mine.forEach((r, i) => {
		if (
			now - r.savedAt > TTL_MS ||
			i >= MAX_THREADS ||
			(keepIds && !keepIds.has(r.conversationId))
		)
			drop.add(r.id);
	});
	if (drop.size) {
		await tx(db, THREADS, "readwrite", (s) => {
			for (const id of drop) s.delete(id);
		});
	}
	// Keys belonging to any other profile go with their records.
	const keyIds = (await tx<IDBValidKey[]>(db, KEYS, "readonly", (s) => s.getAllKeys())) ?? [];
	const foreign = keyIds.filter((k) => k !== profileId);
	if (foreign.length) {
		await tx(db, KEYS, "readwrite", (s) => {
			for (const k of foreign) s.delete(k);
		});
	}
	const key = await tx<CryptoKey>(db, KEYS, "readonly", (s) => s.get(profileId));
	if (!key) return out;
	const undecryptable: string[] = [];
	for (const r of mine) {
		if (drop.has(r.id)) continue;
		try {
			const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: r.iv }, key, r.data);
			out[r.conversationId] = JSON.parse(new TextDecoder().decode(plain));
		} catch {
			// Written under a key that no longer exists: delete it, the
			// network refills the thread and the next save re-encrypts it.
			undecryptable.push(r.id);
		}
	}
	if (undecryptable.length) {
		await tx(db, THREADS, "readwrite", (s) => {
			for (const id of undecryptable) s.delete(id);
		});
	}
	return out;
}

/** Delete everything: sign-out. */
export async function wipeChatVault(): Promise<void> {
	try {
		const db = await dbPromise;
		db?.close();
	} catch {
		/* ignore */
	}
	dbPromise = null;
	keyPromises.clear();
	if (typeof indexedDB === "undefined") return;
	await new Promise<void>((resolve) => {
		try {
			const req = indexedDB.deleteDatabase(DB_NAME);
			req.onsuccess = () => resolve();
			req.onerror = () => resolve();
			req.onblocked = () => resolve();
		} catch {
			resolve();
		}
	});
}
